feat: support for GPT-J HF
PygmalionAI/aphrodite-engine pull request #2
Opened 2023-07-12 17:53 UTC by AlpinDale

Mostly same as upstream:
- Removed code related to training
- Inputs and positions flattened to 1D
- Attention replaced with [`PagedAttentionWithRoPE`](https://github.com/PygmalionAI/aphrodite-engine/blob/fd35ba84b0f6c4a22b6370773393fc2a773959e0/aphrodite/modeling/layers/attention.py#L162)
- Tensor Parallelism (in case we use smaller GPUs to load the model)

2023-07-12 18:43 UTC, TearGosling requested changes

2023-07-12 18:43 UTC, TearGosling commented on aphrodite/modeling/models/gpt_j.py
> +from aphrodite.common.sequence import SequenceOutputs
Seems to be a lot of import errors here?

2023-07-12 18:43 UTC, TearGosling commented on aphrodite/modeling/models/gpt_j.py
> +        self.mlp = GPTJMLP(config)
Pass in `inner_dim` too: `self.mlp = GPTJMLP(inner_dim, config)`

2023-07-14 15:27 UTC, AlpinDale commented
Is this good to merge @TearGosling? Want to finish things up ASAP

2023-07-14 16:30 UTC, TearGosling commented
LGTM!

2023-07-14 16:33 UTC, merged